export const FETCH_LISTITEMS_FAIL = "FETCH_LISTITEMS_FAIL";
export const FETCH_LISTITEMS_START = "FETCH_LISTITEMS_START";
export const FETCH_LISTITEMS_SUCCESS = "FETCH_LISTITEMS_SUCCESS";

export const DECREMENT_QUANTITY = "DECREMENT_QUANTITY";
export const INCREMENT_QUANTITY = "INCREMENT_QUANTITY";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const ADD_TO_CART = "ADD_TO_CART";
export const UPDATE_CART = "UPDATE_CART";
export const UPDATE_TOTAL_PRICE = "UPDATE_TOTAL_PRICE";

export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";

export const SET_FILTER = "SET_FILTER";
export const CLEAR_FILTER = "CLEAR_FILTER";

export const SET_SORT = "SET_SORT";
